site_name: SageWorks
nav:
  - Welcome: index.md
  - Presentations: presentations/index.md
  - Getting Started: getting_started/index.md
  - SageWorks REPL: repl/index.md
  - API Classes: 
    - OverView: api_classes/overview.md
    - Meta: api_classes/meta.md
    - DataSource: api_classes/data_source.md
    - FeatureSet: api_classes/feature_set.md
    - Model: api_classes/model.md
    - Endpoint: api_classes/endpoint.md
    - Views: api_classes/views.md
    - Parameter Store: api_classes/parameter_store.md
    - DataFrame Store: api_classes/df_store.md
    - Pipelines: api_classes/pipelines.md
    - Monitor: api_classes/monitor.md
  - Blogs/Research: 
    - OverView: blogs_research/index.md
    - Residual Analysis: blogs_research/residual_analysis.md 
    - Exploratory Data Analysis(EDA): blogs_research/eda.md
    - High Target Gradients (HTG): blogs_research/htg.md
    - Model Monitoring: blogs_research/model_monitoring.md
  - Core Classes: 
    - OverView: core_classes/overview.md
    - Artifacts: 
      - OverView: core_classes/artifacts/overview.md
      - AthenaSource: core_classes/artifacts/athena_source.md
      - FeatureSetCore: core_classes/artifacts/feature_set_core.md
      - ModelCore: core_classes/artifacts/model_core.md
      - EndpointCore: core_classes/artifacts/endpoint_core.md
      - MonitorCore: core_classes/artifacts/monitor_core.md
      - Artifact: core_classes/artifacts/artifact.md
    - Views:
      - OverView: core_classes/views/overview.md
      - ComputationView: core_classes/views/computation_view.md
      - DisplayView: core_classes/views/display_view.md
      - TrainingView: core_classes/views/training_view.md
      - ModelDataQualityView: core_classes/views/mdq_view.md
    - Transforms: 
      - OverView: core_classes/transforms/overview.md
      - Data Loaders Light: core_classes/transforms/data_loaders_light.md
      - Data Loaders Heavy: core_classes/transforms/data_loaders_heavy.md
      - Data To Features: core_classes/transforms/data_to_features.md
      - Features To Model: core_classes/transforms/features_to_model.md
      - Model to Endpoint: core_classes/transforms/model_to_endpoint.md
      - Pandas Transforms: core_classes/transforms/pandas_transforms.md
      - Transform: core_classes/transforms/transform.md
  - Plugins: 
      - OverView: plugins/index.md
  - Data Algorithms: 
      - OverView: data_algorithms/overview.md
      - DataFrames: data_algorithms/dataframes/overview.md
      - Graphs: data_algorithms/graphs/overview.md
      - Spark: data_algorithms/spark/overview.md
      - SQL: data_algorithms/sql/overview.md
  - SageWorks Enterprise: 
      - OverView: enterprise/index.md
      - Private SaaS: enterprise/private_saas.md
      - Themes: enterprise/themes.md
      - Project Branding: enterprise/project_branding.md
  - FAQ:  misc/faq.md
  - AWS Glue Jobs: glue/index.md 
  - AWS Lambda Layer: lambda_layer/index.md 
  - AWS CloudWatch: cloudwatch/index.md 
  - AWS Setup: 
    - AWS CLI/SSO Setup: aws_setup/aws_setup.md
    - Full Pipeline Testing: aws_setup/full_pipeline.md
    - AWS Admin Initial Setup: aws_setup/core_stack.md
    - Dashboard Setup: aws_setup/dashboard_stack.md
    - Domain/SSL Cert Setup: aws_setup/domain_cert_setup.md
    - AWS Tips and Tricks: aws_setup/aws_tips_and_tricks.md
    - AWS Access Management: aws_setup/aws_access_management.md
    - AWS Client VPN: aws_setup/aws_client_vpn.md
  - Release Notes: 
    - 0.8.23:  release_notes/0_8_23.md
    - 0.8.22:  release_notes/0_8_22.md
    - 0.8.20:  release_notes/0_8_20.md
    - 0.8.11:  release_notes/0_8_11.md
    - 0.8.8:  release_notes/0_8_8.md
    - 0.8.6:  release_notes/0_8_6.md
    - 0.7.8:  release_notes/0_7_8.md
  - Admin: 
    - PyPI Release:  admin/pypi_release.md
    - Base Docker Push:  admin/base_docker_push.md
    - Dashboard Docker Push:  admin/dashboard_docker_push.md
    - Dashboard with Plugins:  admin/dashboard_with_plugins.md
    - Storage:
      - SageWorks Docker for Lambdas:  admin/sageworks_docker_for_lambdas.md

theme:
  name: material
  palette:
    # Palette toggle for light mode
  - scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to light mode

  # Palette toggle for dark mode
  - scheme: default
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

plugins:
- search
- mkdocstrings:
    handlers:
      python:
        paths: [src]

dev_addr: 127.0.0.1:8001
